# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DemoApp' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp

  # SwyftSdk
  pod 'SwyftSdk', :path => '../../swyft-app-ios-sdk'

  pod 'KVNProgress', '~> 2'

end
