# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/swyftstore/swyft-app-ios-sdk-cocoa-pod.git'


target 'DemoApp' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp

  # SwyftSdk
  #pod 'SwyftSdk', '1.0.7-beta'
  pod 'SwyftSdk', :path => '../../swyft-app-ios-sdk'

  pod 'KVNProgress', '~> 2'

end
